### PR TITLE
feat: new landing page

### PR DESCRIPTION
**Pull request by maximousblk**

### CODE REVIEW

**Comment by t8** [comment]
@littledivy would you mind debugging the build preview on Vercel here?

**Review by t8 — COMMENTED** [review]
Max, absolutely incredible job here man. This all looks amazing. Just a few minor tweaks on the first hero-

The button styling looks a bit off compared to the design. Ideally the button border width would be lighter and both buttons the same width as shown here:
image

For context, this is how it currently looks:
image

cc @martonlederer

**Comment by littledivy** [comment]
> @littledivy would you mind debugging the build preview on Vercel here?

sure

**Comment by martonlederer** [comment]
Can we merge this into `feat/clob`? No new additions are needed there and we only need to change a few things on the landing

**Pull request merged**
